/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.oarunshiv.youtube

import java.io.File

fun main(args: Array<String>) {
    val rootDir = getUserResponse("Enter root path of the folder to identify songs: ") {
        val file = File(it)
        file.isDirectory && file.canRead()
    }
    val songFinder = SongFinder()
    val songs = songFinder.listSongs(rootDir)
    println(songs)
}
