/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.oarunshiv.youtube

fun main() {
    val orchestrator = Orchestrator(SongFinder())
    val infoFile = orchestrator.createSongInfoFile()
    println(infoFile)
}
